In [1]:
import os
import math
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from numpy import save

%matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

In [2]:
data_adr = 'data_mar_14'

In [3]:
path_file = os.sep.join([data_adr, 'prihlaska_dim.csv'])
prihlaska_dim = pd.read_csv(path_file, sep=";") 

path_file = os.sep.join([data_adr, 'klasifikace_fact.csv'])
klasifikace_fact = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'predmet_dim.csv'])
predmet_dim = pd.read_csv(path_file, sep=";")

path_file = os.sep.join(['data_mar_17', 'predmet_dim.csv'])
predmet_dim_17 = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'zaverecne_prace_fact.csv'])
prace_fact = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'szzk_dim.csv'])
szzk_dim = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'student_dim.csv'])
student_dim = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'studium_dim.csv'])
studium_dim = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'semestr_dim.csv'])
semestr_dim = pd.read_csv(path_file, sep=";")

path_file = os.sep.join([data_adr, 'zaverecne_prace_dilci_hodnoceni_dim.csv'])
hodnoceni_dim = pd.read_csv(path_file, sep=";")


# bakalar vsechny povinne spolecne predmety
path_file = os.sep.join(['predmety', 'courses_baks.csv'])
courses_baks = pd.read_csv(path_file, sep=",")

# magistr vsechny povinne spolecne predmety
path_file = os.sep.join(['predmety', 'courses_mag.csv'])
courses_mag = pd.read_csv(path_file, sep=",")

In [65]:
len(predmet_dim)

5656

In [67]:
predmet_dim_kody = predmet_dim.predmet_id.unique()

In [68]:
predmet_dim_17[~predmet_dim_17.predmet_id.isin(predmet_dim_kody)]

,predmet_id,studijni_plan_id,kod_predmetu,nazev_predmetu,studijni_plan_kod,studijni_plan_nazev_cs,pocet_kreditu,typ_predmetu,forma_studia,uroven_studia,zpusob_zakonceni,jazyk_vyuky,cislo_dop_sem
5655,12568404,NaN,A0M32IBE,Informační bezpečnost,NaN,NaN,5.0,V,P,M,KZ,CS,NaN
5656,12576204,10240804.0,A0B01LAG,Lineární algebra,BPKYR3,Kybernetika a robotika - Systémy a řízení,7.0,P,P,B,"Z,ZK",CS,1.0
5657,12576204,10240704.0,A0B01LAG,Lineární algebra,BPKYR2,Kybernetika a robotika - Senzory a přístrojová...,7.0,P,P,B,"Z,ZK",CS,1.0
5658,12576204,10242704.0,A0B01LAG,Lineární algebra,BPOI1,Otevřená informatika - Počítačové systémy,7.0,P,P,B,"Z,ZK",CS,1.0
5659,12576204,10242804.0,A0B01LAG,Lineární algebra,BPOI2,Otevřená informatika - Informatika a počítačov...,7.0,P,P,B,"Z,ZK",CS,1.0
5660,12576204,30000063.0,A0B01LAG,Lineární algebra,BPKYR_BO,Kybernetika a robotika - před rozřazením do oborů,7.0,P,P,B,"Z,ZK",CS,1.0
5661,12576204,10240604.0,A0B01LAG,Lineární algebra,BPKYR1,Kybernetika a robotika - Robotika,7.0,P,P,B,"Z,ZK",CS,1.0
5662,12576204,10242904.0,A0B01LAG,Lineární algebra,BPOI3,Otevřená informatika - Softwarové systémy,7.0,P,P,B,"Z,ZK",CS,1.0
5663,12576204,30000065.0,A0B01LAG,Lineární algebra,BPOI_BO,Otevřená informatika - před rozřazením do oborů,7.0,P,P,B,"Z,ZK",CS,1.0

## SZZK

In [4]:
szzk_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13552 entries, 0 to 13551
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statni_zkouska_id   13552 non-null  int64
 1   zaverecna_prace_id  4257 non-null   float64
 2   studium_id          13552 non-null  int64
 3   cislo_terminu       13552 non-null  int64
 4   typ_szzk            13552 non-null  object
 5   uzavreno            889 non-null    object
 6   datum_prihlaseni    2818 non-null   object
 7   datum_absolvovani   1953 non-null   object
 8   celkove_hodnoceni   3792 non-null   float64
 9   poznamka            9 non-null      object
dtypes: float64(2), int64(3), object(5)
memory usage: 1.0+ MB

In [5]:
ukonceno = studium_dim[studium_dim.studuje == 'K'].studium_id.unique()

In [59]:
len(ukonceno)

14317

In [60]:
len(successful_students_bak)

2111

In [61]:
len(failed_students_bak)

5919

In [6]:
szzk_id_ukon = szzk_dim[(szzk_dim.studium_id.isin(ukonceno))].statni_zkouska_id.unique()

In [46]:
szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
        & (szzk_dim.celkove_hodnoceni.isna())]

,statni_zkouska_id,zaverecna_prace_id,studium_id,cislo_terminu,typ_szzk,uzavreno,datum_prihlaseni,datum_absolvovani,celkove_hodnoceni,poznamka
2,438372649605,4.383726e+11,1565806,1,SZZ,NaN,NaN,NaN,NaN,NaN
3,422187805805,4.221878e+11,1565906,1,SZZ,NaN,NaN,NaN,NaN,NaN
15,415677911605,3.329849e+11,1568706,1,SZZ,NaN,NaN,NaN,NaN,NaN
27,421576193805,4.211639e+11,1571706,1,SZZ,NaN,NaN,NaN,NaN,NaN
37,328577791905,NaN,1574806,1,SZZ,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
13542,1241009331705,NaN,19946906,1,SZZ,NaN,NaN,NaN,NaN,NaN
13543,1241020995405,NaN,19948606,1,SZZ,NaN,NaN,NaN,NaN,NaN
13544,1241021175405,NaN,19948906,1,SZZ,NaN,NaN,NaN,NaN,NaN
13546,1241021488005,NaN,19952506,1,SZZ,NaN,NaN,NaN,NaN,NaN
13547,1241021541305,NaN,19952706,1,SZZ,NaN,NaN,NaN,NaN,NaN

In [63]:
szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
         & (szzk_dim.studium_id.isin(successful_students_bak))
        & (szzk_dim.celkove_hodnoceni.isna())]

,statni_zkouska_id,zaverecna_prace_id,studium_id,cislo_terminu,typ_szzk,uzavreno,datum_prihlaseni,datum_absolvovani,celkove_hodnoceni,poznamka
827,764807826705,6.322227e+11,4764606,2,SZZ4,NaN,NaN,NaN,NaN,NaN
1323,763431760605,7.245805e+11,6258706,2,SZZ4,NaN,NaN,NaN,NaN,NaN
1600,782342369705,7.201839e+11,6320006,2,SZZ4,NaN,NaN,NaN,NaN,NaN
7545,862366073605,1.210889e+12,14318106,1,SZZ,NaN,NaN,NaN,NaN,NaN
8143,961987128205,1.239474e+12,15553506,1,SZZ,NaN,NaN,NaN,NaN,NaN
8168,961987144605,1.239420e+12,15556006,1,SZZ,NaN,NaN,NaN,NaN,NaN
8290,961987223805,1.239555e+12,15568106,1,SZZ,NaN,NaN,NaN,NaN,NaN
8411,961987301805,1.240305e+12,15580206,1,SZZ,NaN,NaN,NaN,NaN,NaN
8726,961987512505,1.240299e+12,15611706,1,SZZ,NaN,NaN,NaN,NaN,NaN
9285,987296541905,1.239721e+12,16195406,1,SZZ,NaN,NaN,NaN,NaN,NaN
9920,1065790501105,1.239589e+12,16728806,1,SZZ,NaN,NaN,NaN,NaN,NaN
10037,1065790580205,1.240572e+12,16740506,1,SZZ,NaN,NaN,NaN,NaN,NaN
10203,1065790689105,NaN,16757106,1,SZZ,NaN,NaN,NaN,NaN,NaN

In [44]:
szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
         & (szzk_dim.studium_id.isin(failed_students_bak))
        & (szzk_dim.celkove_hodnoceni.isna())]

,statni_zkouska_id,zaverecna_prace_id,studium_id,cislo_terminu,typ_szzk,uzavreno,datum_prihlaseni,datum_absolvovani,celkove_hodnoceni,poznamka
2,438372649605,4.383726e+11,1565806,1,SZZ,NaN,NaN,NaN,NaN,NaN
3,422187805805,4.221878e+11,1565906,1,SZZ,NaN,NaN,NaN,NaN,NaN
15,415677911605,3.329849e+11,1568706,1,SZZ,NaN,NaN,NaN,NaN,NaN
27,421576193805,4.211639e+11,1571706,1,SZZ,NaN,NaN,NaN,NaN,NaN
37,328577791905,NaN,1574806,1,SZZ,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
13467,1240981667905,NaN,19811906,1,SZZ,NaN,NaN,NaN,NaN,NaN
13471,1240981670805,NaN,19812306,1,SZZ,NaN,NaN,NaN,NaN,NaN
13474,1240981672605,NaN,19812606,1,SZZ,NaN,NaN,NaN,NaN,NaN
13493,1240981685005,NaN,19814506,1,SZZ,NaN,NaN,NaN,NaN,NaN
13510,1240981696505,NaN,19816206,1,SZZ,NaN,NaN,NaN,NaN,NaN

In [48]:
szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
         & (szzk_dim.studium_id.isin(failed_students_mag))
        & (szzk_dim.celkove_hodnoceni.isna())]

,statni_zkouska_id,zaverecna_prace_id,studium_id,cislo_terminu,typ_szzk,uzavreno,datum_prihlaseni,datum_absolvovani,celkove_hodnoceni,poznamka
199,335540448505,NaN,3684106,1,SZZ,NaN,NaN,NaN,NaN,NaN
209,348912571905,NaN,3685506,1,SZZ,NaN,NaN,NaN,NaN,NaN
219,307763805705,3.077638e+11,3686506,1,SZZ,NaN,NaN,NaN,NaN,NaN
221,346997580805,NaN,3686706,1,SZZ,NaN,NaN,NaN,NaN,NaN
252,328822320305,2.059908e+11,3690406,1,SZZ,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
13406,1240956182405,NaN,19797406,1,SZZ,NaN,NaN,NaN,NaN,NaN
13408,1240956184005,NaN,19797606,1,SZZ,NaN,NaN,NaN,NaN,NaN
13411,1240956186105,NaN,19797906,1,SZZ,NaN,NaN,NaN,NaN,NaN
13416,1240956189405,NaN,19798406,1,SZZ,NaN,NaN,NaN,NaN,NaN
13423,1240956194305,NaN,19799106,1,SZZ,NaN,NaN,NaN,NaN,NaN

In [64]:
szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
         & (szzk_dim.studium_id.isin(successful_students_mag))
        & (szzk_dim.celkove_hodnoceni.isna())]

,statni_zkouska_id,zaverecna_prace_id,studium_id,cislo_terminu,typ_szzk,uzavreno,datum_prihlaseni,datum_absolvovani,celkove_hodnoceni,poznamka
2349,760937902005,5.655188e+11,8332706,2,SZZ4,NaN,NaN,NaN,NaN,NaN
2366,761770155005,6.901142e+11,8334806,2,SZZ4,NaN,NaN,NaN,NaN,NaN
2397,760937899705,7.173313e+11,8339106,2,SZZ4,NaN,NaN,NaN,NaN,NaN
2457,761770154305,7.245842e+11,8373706,2,SZZ4,NaN,NaN,NaN,NaN,NaN
3397,760937902705,7.168112e+11,9238506,2,SZZ4,NaN,NaN,NaN,NaN,NaN
3454,761215275905,7.165572e+11,9243806,2,SZZ2,NaN,NaN,NaN,NaN,NaN
3484,761215276605,7.092909e+11,9246606,2,SZZ4,NaN,NaN,NaN,NaN,NaN
8896,1240538500805,1.202893e+12,15628606,2,SZZ,NaN,NaN,NaN,NaN,NaN
8966,962290817905,1.239610e+12,15635606,1,SZZ,NaN,NaN,NaN,NaN,NaN
9030,962290872605,1.133206e+12,15641906,1,SZZ,NaN,NaN,NaN,NaN,NaN
9521,1065781916005,1.235389e+12,16688406,1,SZZ,NaN,NaN,NaN,NaN,NaN
9522,1065781916805,1.240780e+12,16688506,1,SZZ,NaN,NaN,NaN,NaN,NaN
9523,1065781917905,1.240761e+12,16688606,1,SZZ,NaN,NaN,NaN,NaN,NaN
9530,1065782031805,1.239474e+12,16689406,1,SZZ,NaN,NaN,NaN,NaN,NaN
9531,1065782087705,1.239580e+12,16689606,1,SZZ,NaN,NaN,NaN,NaN,NaN
9537,1065782092605,1.239532e+12,16690206,1,SZZ,NaN,NaN,NaN,NaN,NaN
9550,1065782103305,1.234771e+12,16691506,1,SZZ,NaN,NaN,NaN,NaN,NaN
9563,1065782113705,1.239439e+12,16692806,1,SZZ,NaN,NaN,NaN,NaN,NaN
9564,1065782114505,1.239434e+12,16692906,1,SZZ,NaN,NaN,NaN,NaN,NaN
9566,1065782116205,1.239637e+12,16693106,1,SZZ,NaN,NaN,NaN,NaN,NaN
9579,1065782127005,1.240833e+12,16694406,1,SZZ,NaN,NaN,NaN,NaN,NaN
9583,1065782130605,NaN,16694806,1,SZZ,NaN,NaN,NaN,NaN,NaN
9584,1065782131405,1.240285e+12,16694906,1,SZZ,NaN,NaN,NaN,NaN,NaN
9592,1065782137805,1.238387e+12,16695706,1,SZZ,NaN,NaN,NaN,NaN,NaN
9610,1065782152905,1.240406e+12,16697506,1,SZZ,NaN,NaN,NaN,NaN,NaN
9613,1065782155305,1.240246e+12,16697806,1,SZZ,NaN,NaN,NaN,NaN,NaN
9615,1065782156705,NaN,16698006,1,SZZ,NaN,NaN,NaN,NaN,NaN
9622,1065782162205,1.239721e+12,16698706,1,SZZ,NaN,NaN,NaN,NaN,NaN
10446,1088201552805,1.240977e+12,17204306,1,SZZ,NaN,NaN,NaN,NaN,NaN
10453,1088201558605,1.239472e+12,17205006,1,SZZ,NaN,NaN,NaN,NaN,NaN
10471,1088201583005,1.239435e+12,17206706,1,SZZ,NaN,NaN,NaN,NaN,NaN
10958,1179143665605,NaN,17888506,1,SZZ,NaN,NaN,NaN,NaN,NaN
11686,1198415954005,1.240258e+12,18395506,1,SZZ,NaN,NaN,NaN,NaN,NaN
11742,1201006840405,1.239610e+12,18530006,1,SZZ,NaN,NaN,NaN,NaN,NaN

In [51]:
nemaj_szz_ne_mag_bak = szzk_dim[(szzk_dim.studium_id.isin(ukonceno))
         & (~szzk_dim.studium_id.isin(failed_students_mag))
         & (~szzk_dim.studium_id.isin(failed_students_bak))
         & (~szzk_dim.studium_id.isin(successful_students_bak))
         & (~szzk_dim.studium_id.isin(successful_students_mag))
        & (szzk_dim.celkove_hodnoceni.isna())].studium_id.unique()

In [57]:
studium_dim[(studium_dim.studium_id.isin(nemaj_szz_ne_mag_bak))
           & (studium_dim.forma_studia == 'P')]

,studium_id,typ_programu,forma_studia,datum_zahajeni,datum_ukonceni,rocnik,studijni_stav,studuje,zamereni_id,fakulta_id,nazev_fakulty,jazyk_vyuky,ukonceni_zpusob,platby_stav,pruchod,rok_maturity,odkud_skola_kod
1887,19657706,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,1.221572e+12,2019,999999050.0
1889,19060706,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999704.0
1890,19656606,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,1.211790e+12,2020,999999792.0
1891,19656306,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,1.221572e+12,2019,999999643.0
1895,19875506,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2016,999999762.0
1896,19335606,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999031.0
1899,19090806,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999100.0
1900,19325706,B,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2021,555555555.0
1902,19658006,B,P,2021,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999792.0
1936,19952706,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2016,999999417.0
1937,19948906,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2016,999999804.0
1940,19462906,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2016,999999356.0
1941,19460206,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2017,999999356.0
1943,19224706,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2016,999999999.0
1944,19212606,B,P,2021,2021,1.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2013,999999807.0
1973,19657506,N,P,2021,2022,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,1.220966e+12,0,NaN
1981,18489506,B,P,2020,2022,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999840.0
1982,17719706,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999792.0
1983,17027506,B,P,2019,2022,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999792.0
1986,18487806,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999804.0
1987,18579906,B,P,2020,2022,2.0,17,K,NaN,10,Fakulta informačních technologií,EN,1.0,NaN,NaN,2018,999999784.0
1988,14880506,B,P,2017,2022,5.0,17,K,NaN,10,Fakulta informačních technologií,EN,1.0,NaN,NaN,2017,999999643.0
1989,17038906,B,P,2019,2022,3.0,17,K,NaN,10,Fakulta informačních technologií,EN,1.0,NaN,NaN,2017,999999792.0
1990,19333206,B,P,2021,2022,1.0,17,K,NaN,10,Fakulta informačních technologií,EN,1.0,NaN,NaN,2016,999999999.0
1991,18214606,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999156.0
1992,18487906,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999643.0
1993,14932206,B,P,2017,2022,5.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999031.0
1996,17699206,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999031.0
1998,17198606,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999792.0
1999,13534906,B,P,2016,2017,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,999999792.0
2000,15934606,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2018,999999356.0
2001,14974806,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999784.0
2002,14765906,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999792.0
2003,15979606,B,P,2018,2019,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2018,999999440.0
2004,13679506,B,P,2016,2017,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2016,999999051.0
2005,14892806,B,P,2017,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999804.0
2006,13702506,B,P,2016,2017,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,999999504.0
2007,14969206,B,P,2017,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999792.0
2008,13535306,B,P,2016,2017,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,999999840.0
2009,13706706,B,P,2016,2017,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999031.0
2010,12174406,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2012,10020406,B,P,2014,2015,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,NaN
2014,9659006,B,P,2014,2014,1.0,39,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999586.0
2016,18488406,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999398.0
2018,18311706,B,P,2020,2022,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999643.0
2021,17720606,B,P,2020,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,6.217132e+11,2017,999999804.0
2033,12084106,B,P,2015,2016,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999112.0
2034,12083606,B,P,2015,2016,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2010,999999356.0
2036,12080606,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999031.0
2038,12080806,B,P,2015,2018,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,999999999.0
2040,12083106,B,P,2015,2016,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,999999050.0
2041,12082806,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999999.0
2043,12081706,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999398.0
2044,12081106,B,P,2015,2016,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2003,999999270.0
2045,12082206,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999156.0
2047,12082406,B,P,2015,2017,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999398.0
2049,10284606,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2009,NaN
2050,9659406,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999031.0
2051,9659306,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,999999643.0
2052,9658806,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999784.0
2053,9659106,B,P,2014,2015,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,999999704.0
2054,9658406,B,P,2014,2014,1.0,39,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2008,999999566.0
2055,9658506,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,999999398.0
2056,9659206,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2010,999999792.0
2057,9658606,B,P,2014,2015,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999398.0
2058,9658906,B,P,2014,2014,1.0,39,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2006,999999566.0
2059,9659706,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,999999398.0
2060,9659506,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2010,999999752.0
2061,9661806,B,P,2014,2015,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2011,999999398.0
2063,9689306,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2064,9689406,B,P,2014,2015,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,NaN
2065,12183206,B,P,2015,2016,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2012,555555555.0
2066,9992406,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2006,NaN
2067,9690206,B,P,2014,2015,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,NaN
2068,9760506,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2070,9759406,B,P,2014,2015,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,NaN
2071,8390806,B,P,2013,2015,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,NaN
2073,8665106,B,P,2013,2015,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2074,8439006,B,P,2013,2014,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,NaN
2075,8439106,B,P,2013,2014,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2078,8599406,B,P,2013,2014,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2006,NaN
2079,7822506,B,P,2013,2014,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,0.0,NaN,2009,999999999.0
2082,8572606,B,P,2013,2014,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2083,8846406,B,P,2014,2014,1.0,39,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,999999398.0
2084,8576906,B,P,2013,2015,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2085,8577006,B,P,2013,2015,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,NaN
2089,7115106,B,P,2012,2014,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,0.0,NaN,2012,NaN
2103,4261306,B,P,2010,2012,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,0.0,NaN,0,NaN
2106,9663706,B,P,2014,2016,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2012,NaN
2107,9612606,B,P,2014,2015,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,NaN
2108,12080906,B,P,2015,2016,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2012,999999031.0
2111,17388206,B,P,2019,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999398.0
2112,17011506,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,999999372.0
2113,18489006,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999356.0
2114,12082706,B,P,2015,2016,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999356.0
2119,18489206,B,P,2020,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2020,999999398.0
2134,17883906,B,P,2020,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999156.0
2135,17729506,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,555555555.0
2136,18487606,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999031.0
2137,18490106,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,999999840.0
2138,18500606,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999762.0
2139,17047006,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999417.0
2144,17203006,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999031.0
2148,17035206,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999999.0
2151,15934906,B,P,2018,2021,4.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.214750e+11,2017,999999356.0
2155,17203106,B,P,2019,2021,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999031.0
2156,18271106,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999031.0
2157,18489606,B,P,2020,2021,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2019,999999860.0
2158,18488206,B,P,2020,2021,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2020,999999999.0
2159,18001106,B,P,2020,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999840.0
2160,18489906,B,P,2020,2021,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2015,999999250.0
2161,18489306,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999804.0
2162,15997506,B,P,2018,2021,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2016,999999818.0
2163,17165206,B,P,2019,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999807.0
2164,17726506,B,P,2020,2021,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2016,999999792.0
2165,14962606,B,P,2017,2021,4.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2015,999999356.0
2166,17115806,B,P,2019,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999840.0
2167,18109606,B,P,2020,2021,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999804.0
2168,17899806,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999840.0
2169,17208006,B,P,2019,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999356.0
2170,18488906,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2020,999999784.0
2171,17379906,B,P,2019,2021,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999999.0
2172,18576506,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999031.0
2173,17761106,B,P,2020,2021,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999762.0
2174,17341406,B,P,2019,2021,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999804.0
2175,15996206,B,P,2018,2020,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2010,999999398.0
2176,13670106,B,P,2016,2018,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999356.0
2177,13534806,B,P,2016,2019,4.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999417.0
2178,18489106,B,P,2020,2020,1.0,39,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999792.0
2179,17196206,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999400.0
2180,14778906,B,P,2017,2020,4.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2012,999999840.0
2181,17139706,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999760.0
2182,17338506,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,999999792.0
2183,17166506,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999792.0
2184,14956706,B,P,2017,2020,4.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999095.0
2185,14963506,B,P,2017,2020,4.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,1997,999999417.0
2186,17416706,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999792.0
2187,17216206,B,P,2019,2020,2.0,6,K,NaN,10,Fakulta informačních technologií,EN,9.0,NaN,NaN,2019,999999498.0
2188,17021106,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999398.0
2190,17068406,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999792.0
2191,17085606,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999792.0
2192,17078506,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999643.0
2193,15430806,B,P,2018,2020,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999762.0
2194,17165606,B,P,2019,2020,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2019,999999112.0
2195,17212706,B,P,2019,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999156.0
2197,17269606,B,P,2019,2020,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2018,999999156.0
2198,16202506,B,P,2018,2020,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2016,999999840.0
2200,17253706,B,P,2019,2020,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2019,999999804.0
2201,17337006,B,P,2019,2020,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2015,999999643.0
2202,16151106,B,P,2018,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2017,999999031.0
2203,17388106,B,P,2019,2020,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,999999356.0
2204,17413206,B,P,2019,2020,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2019,999999398.0
2205,15998206,B,P,2018,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999804.0
2206,16008606,B,P,2018,2020,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,6.217132e+11,2016,999999410.0
2208,16125106,B,P,2018,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999792.0
2209,16202206,B,P,2018,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217132e+11,2018,999999031.0
2210,17207206,B,P,2019,2020,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999792.0
2211,17341106,B,P,2019,2020,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2015,999999784.0
2212,15996706,B,P,2018,2020,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217132e+11,2017,999999398.0
2215,17468806,B,P,2019,2020,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999398.0
2216,17387806,B,P,2019,2020,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2019,999999398.0
2217,12081406,B,P,2015,2016,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999792.0
2219,14789606,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999784.0
2220,14930006,B,P,2017,2019,3.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2017,999999999.0
2221,16181506,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999268.0
2222,16174806,B,P,2018,2019,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2017,999999398.0
2223,16101006,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2018,999999031.0
2224,15979506,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2018,999999999.0
2225,16020406,B,P,2018,2019,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,6.217132e+11,2017,999999156.0
2226,14764406,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2011,999999792.0
2227,15997606,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2001,999999076.0
2228,14893806,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2013,999999807.0
2229,16021406,B,P,2018,2019,2.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,6.217131e+11,2016,999999398.0
2230,15979706,B,P,2018,2019,2.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217132e+11,2018,999999840.0
2231,14970506,B,P,2017,2019,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999682.0
2232,16151306,B,P,2018,2019,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2017,999999804.0
2234,16215306,B,P,2018,2019,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2013,999999792.0
2235,16151606,B,P,2018,2019,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,6.217132e+11,2015,999999250.0
2236,15925406,B,P,2018,2019,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,6.217131e+11,2016,999999784.0
2237,16003106,B,P,2018,2019,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2016,999999356.0
2238,16216206,B,P,2018,2019,1.0,7,K,NaN,10,Fakulta informačních technologií,EN,3.0,NaN,NaN,2014,999999275.0
2239,13655006,B,P,2016,2018,3.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2014,999999275.0
2240,13506106,B,P,2016,2017,1.0,3,K,NaN,10,Fakulta informačních technologií,EN,2.0,NaN,NaN,2016,999999246.0

In [54]:
studium_dim.studijni_stav.unique()

array(['1', '38', '39', '3', '6', 'R', '8', '7', '17', '16', '88', '34',
       '18'], dtype=object)

## Hodnoceni

In [8]:
hodnoceni_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4975 entries, 0 to 4974
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   statni_zkouska_id  4975 non-null   int64
 1   cislo_terminu      4975 non-null   int64
 2   predmet_cislo      4975 non-null   int64
 3   datum              2654 non-null   object
 4   hodnoceni          3407 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 194.5+ KB

In [9]:
hodnoceni_dim[(hodnoceni_dim.statni_zkouska_id.isin(szzk_id_ukon))]

      statni_zkouska_id  cislo_terminu  predmet_cislo       datum  hodnoceni
0          244063669505              1              1         NaN        NaN
1          244063720505              1              1         NaN        NaN
2          246871338705              1              1         NaN        NaN
3          246873049205              1              1         NaN        NaN
4          246873920305              1              1         NaN        NaN
...                 ...            ...            ...         ...        ...
4970      1183193996005              2              1  2020-06-23        3.0
4971      1183193996105              2              1  2020-06-23        4.0
4972      1183505661805              2              1  2020-09-07        2.0
4973      1183816699405              2              1  2020-06-25        4.0
4974      1183816699505              2              1  2020-06-25        2.5

[4969 rows x 5 columns]

In [10]:
hodnoceni_dim[(hodnoceni_dim.statni_zkouska_id.isin(szzk_id_ukon))
             & (hodnoceni_dim.hodnoceni.notna())]

      statni_zkouska_id  cislo_terminu  predmet_cislo       datum  hodnoceni
51         307763643005              1              1         NaN        1.5
52         307763804805              1              1  2012-06-08        1.0
54         322730046105              1              1  2012-06-07        2.0
55         323003956005              1              1  2012-06-07        2.0
56         324349514805              1              1  2012-06-07        2.0
...                 ...            ...            ...         ...        ...
4970      1183193996005              2              1  2020-06-23        3.0
4971      1183193996105              2              1  2020-06-23        4.0
4972      1183505661805              2              1  2020-09-07        2.0
4973      1183816699405              2              1  2020-06-25        4.0
4974      1183816699505              2              1  2020-06-25        2.5

[3407 rows x 5 columns]

## Prihlaska

In [11]:
studium_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16570 entries, 0 to 16569
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   studium_id       16570 non-null  int64
 1   typ_programu     16570 non-null  object
 2   forma_studia     13883 non-null  object
 3   datum_zahajeni   16570 non-null  object
 4   datum_ukonceni   14317 non-null  object
 5   rocnik           16557 non-null  float64
 6   studijni_stav    16570 non-null  object
 7   studuje          16570 non-null  object
 8   zamereni_id      4 non-null      float64
 9   fakulta_id       16570 non-null  int64
 10  nazev_fakulty    16570 non-null  object
 11  jazyk_vyuky      16021 non-null  object
 12  ukonceni_zpusob  14317 non-null  float64
 13  platby_stav      8826 non-null   float64
 14  pruchod          610 non-null    float64
 15  rok_maturity     11869 non-null  object
 16  odkud_skola_kod  10963 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 2.1+ MB

In [12]:
prihlaska_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 97 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cislo_prihlasky              324 non-null    int64
 1   odkud_uchazec_prihlasen_kod  102 non-null    float64
 2   prihlaska_kod                324 non-null    int64
 3   studium_id                   324 non-null    int64
 4   rozhodnuti_kod               324 non-null    int64
 5   obor_ss_kod                  0 non-null      float64
 6   ss_izo                       26 non-null     float64
 7   ss_typ                       0 non-null      float64
 8   ss_predmet1                  0 non-null      float64
 9   ss_predmet2                  0 non-null      float64
 10  ss_predmet3                  0 non-null      float64
 11  ss_predmet4                  0 non-null      float64
 12  ss_predmet5                  0 non-null      float64
 13  ss_predmet1_znamky           0 non-null      float64
 14  ss_predmet2_znamky           0 non-null      float64
 15  ss_predmet3_znamky           0 non-null      float64
 16  ss_predmet4_znamky           0 non-null      float64
 17  ss_predmet5_znamky           0 non-null      float64
 18  ss_predmet1_prumer           0 non-null      float64
 19  ss_predmet2_prumer           0 non-null      float64
 20  ss_predmet3_prumer           0 non-null      float64
 21  ss_predmet4_prumer           0 non-null      float64
 22  ss_predmet5_prumer           0 non-null      float64
 23  ss_prumer_prumeru            0 non-null      float64
 24  ss_prumer_znamek             0 non-null      float64
 25  bakalar_prumer               0 non-null      float64
 26  predchozi_studium            192 non-null    object
 27  doplnujici_udaj1             0 non-null      float64
 28  doplnujici_udaj2             0 non-null      float64
 29  doplnujici_udaj3             0 non-null      float64
 30  doplnujici_udaj4             8 non-null      object
 31  typ_prihlasky                324 non-null    object
 32  maturita_znamky              0 non-null      float64
 33  maturita_prumer              0 non-null      float64
 34  maturita_predmety            0 non-null      float64
 35  maturita_rok                 83 non-null     float64
 36  cislo_mistnosti_pz           0 non-null      float64
 37  datum_pz                     0 non-null      float64
 38  prominuti_pz                 18 non-null     float64
 39  hodnoceni_pz                 243 non-null    float64
 40  hodnoceni_pz_cast1           0 non-null      float64
 41  hodnoceni_pz_cast2           0 non-null      float64
 42  hodnoceni_pz_cast3           0 non-null      float64
 43  hodnoceni_pz_cast4           0 non-null      float64
 44  hodnoceni_pz_cast5           0 non-null      float64
 45  hodnoceni_pz_cast6           0 non-null      float64
 46  hodnoceni_pz_cast7           0 non-null      float64
 47  hodnoceni_pz_cast8           0 non-null      float64
 48  hodnoceni_pz_cast9           0 non-null      float64
 49  hodnoceni_pz_cast10          0 non-null      float64
 50  hodnoceni_pz_cast11          0 non-null      float64
 51  hodnoceni_pz_cast12          0 non-null      float64
 52  zapsal_ke_studiu             2 non-null      float64
 53  status                       0 non-null      float64
 54  stipendium                   65 non-null     object
 55  stipendium_cizi              0 non-null      float64
 56  kolej_zadost                 52 non-null     float64
 57  termin                       0 non-null      float64
 58  prechodne                    2 non-null      float64
 59  studijni_skupina             6 non-null      float64
 60  nove_prijaty                 308 non-null    object
 61  navazujici_stud_program      4 non-null      object
 62  trvaly_pobyt_v_cr            320 non-null    object
 63  financovani                  324 non-null    int64
 64  stupen_predchoziho_vzdelani  324 non-null    object
 65  pz1_datum                    0 non-null      float64
 66  pz1_cas                      0 non-null      float64
 67  pz1_mistnost                 0 non-null      float64
 68  pz2_datum                    0 non-null      float64
 69  pz2_cas                      0 non-null      float64
 70  pz2_mistnost                 0 non-null      float64
 71  pz3_datum                    0 non-null      float64
 72  pz3_cas                      0 non-null      float64
 73  pz3_mistnost                 0 non-null      float64
 74  pisemny_test                 0 non-null      float64
 75  anketa_odkud_kod             1 non-null      float64
 76  anketa_odkud_poznamka        0 non-null      float64
 77  cislo_uchazece               266 non-null    float64
 78  scio_test                    0 non-null      float64
 79  olympiady                    0 non-null      float64
 80  postizeni_kod                0 non-null      float64
 81  postizeni_poznamka           0 non-null      float64
 82  placeno_r                    0 non-null      float64
 83  placeno_poznamka             0 non-null      float64
 84  placeno_mail                 0 non-null      float64
 85  staz_stat                    2 non-null      float64
 86  staz_poznamka                0 non-null      float64
 87  maturita_uroven              0 non-null      float64
 88  zajem                        0 non-null      float64
 89  zprava_pro_uchazece          0 non-null      float64
 90  priorita                     0 non-null      float64
 91  datum_registrace             324 non-null    object
 92  datum_rozhodnuti             266 non-null    object
 93  misto_kod                    255 non-null    object
 94  okres_kod                    272 non-null    float64
 95  zeme_kod                     316 non-null    float64
 96  psc                          279 non-null    float64
dtypes: float64(81), int64(5), object(11)
memory usage: 245.7+ KB

## Klasifikace

In [13]:
klasifikace_fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347031 entries, 0 to 347030
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   semestr_id     347031 non-null  object
 1   predmet_id     343430 non-null  float64
 2   studium_id     347031 non-null  int64
 3   zapocteno      246340 non-null  object
 4   zakonceno      236678 non-null  float64
 5   znamka         207166 non-null  float64
 6   poradi_zapisu  343430 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 18.5+ MB

In [14]:
#slovnik predmet_id: kod_predmetu
courses_tran_id_kod = dict()
for index, row in predmet_dim.iterrows():
    courses_tran_id_kod[row['predmet_id']] = row['kod_predmetu']
    
#slovnik kod_predmetu: predmet_id
courses_tran_kod_id = dict()
for index, row in predmet_dim.iterrows():
    courses_tran_kod_id[row['kod_predmetu']] = row['predmet_id']

In [15]:
klasifikace_fact[(klasifikace_fact.studium_id == 12375406) & (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-MLO'])]

,semestr_id,predmet_id,studium_id,zapocteno,zakonceno,znamka,poradi_zapisu
43633,A000,1121306.0,12375406,Z,1.0,2.5,1.0

In [16]:
# PA1
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIK-PA1'], 
      courses_tran_kod_id['BIE-PA1'], 
      courses_tran_kod_id['BI-PA1.21'], 
      courses_tran_kod_id['BIE-PA1.21'],
      courses_tran_kod_id['BIK-PA1.21']],
     
      courses_tran_kod_id['BI-PA1']
     )

#PAI
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIK-PAI'], 
      courses_tran_kod_id['BIE-PAI'], 
      courses_tran_kod_id['BI-PAI.21'], 
      courses_tran_kod_id['BIE-PAI.21'],
      courses_tran_kod_id['BIK-PAI.21']],
     
      courses_tran_kod_id['BI-PAI']
     )

#ZMA
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIK-ZMA'], 
      courses_tran_kod_id['BIE-ZMA']],
     
    courses_tran_kod_id['BI-ZMA']
     )
klasifikace_fact

#CAO
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIK-CAO'], 
      courses_tran_kod_id['BIE-CAO'], 
      courses_tran_kod_id['BI-TZP.21'], 
      courses_tran_kod_id['BIE-TZP.21'],
      courses_tran_kod_id['BIK-TZP.21']],
     
      courses_tran_kod_id['BI-CAO']
     )

#CAO
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BI-UOS'], 
      courses_tran_kod_id['BIE-UOS'], 
      courses_tran_kod_id['BIK-UOS'], 
      courses_tran_kod_id['BI-UOS.21'],
      courses_tran_kod_id['BIK-UOS.21'],
      courses_tran_kod_id['BIE-PS1'],
      courses_tran_kod_id['BIK-PS1'],
      courses_tran_kod_id['BIE-UOS.21']],
     
      courses_tran_kod_id['BI-PS1']
     )

#MLO
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIK-MLO'], 
      courses_tran_kod_id['BIE-MLO']],
     
      courses_tran_kod_id['BI-MLO']
     )

#PA2
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-PA2'], 
      courses_tran_kod_id['BIK-PA2'], 
      courses_tran_kod_id['BI-PA2.21'], 
      courses_tran_kod_id['BIE-PA2.21'],
      courses_tran_kod_id['BIK-PA2.21']],
     
      courses_tran_kod_id['BI-PA2']
     )

#SAP
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-SAP'], 
      courses_tran_kod_id['BIK-SAP'], 
      courses_tran_kod_id['BI-SAP.21'], 
      courses_tran_kod_id['BIE-SAP.21'],
      courses_tran_kod_id['BIK-SAP.21']],
     
      courses_tran_kod_id['BI-SAP']
     )

#DBS
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-DBS'], 
      courses_tran_kod_id['BIK-DBS'], 
      courses_tran_kod_id['BI-DBS.21'], 
      courses_tran_kod_id['BIE-DBS.21'],
      courses_tran_kod_id['BIK-DBS.21']],
     
      courses_tran_kod_id['BI-DBS']
     )

#LIN
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-LIN'], 
      courses_tran_kod_id['BIK-LIN']],
     
      courses_tran_kod_id['BI-LIN']
     )

#AAG
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-AAG'], 
      courses_tran_kod_id['BIK-AAG'], 
      courses_tran_kod_id['BI-AAG.21'], 
      courses_tran_kod_id['BIE-AAG.21'],
      courses_tran_kod_id['BIK-AAG.21']],
     
      courses_tran_kod_id['BI-AAG']
     )

#ZDM
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-ZDM'], 
      courses_tran_kod_id['BIK-ZDM']],
     
      courses_tran_kod_id['BI-ZDM']
     )

#OSY
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-OSY'], 
      courses_tran_kod_id['BIK-OSY'], 
      courses_tran_kod_id['BI-OSY.21'], 
      courses_tran_kod_id['BIE-OSY.21'],
      courses_tran_kod_id['BIK-OSY.21']],
     
      courses_tran_kod_id['BI-OSY']
     )

#PSI
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-PSI'], 
      courses_tran_kod_id['BIK-PSI'], 
      courses_tran_kod_id['BI-PSI.21'], 
      courses_tran_kod_id['BIE-PSI.21'],
      courses_tran_kod_id['BIK-PSI.21']],
     
      courses_tran_kod_id['BI-PSI']
     )

#BEZ
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-BEZ'], 
      courses_tran_kod_id['BIK-BEZ']],
     
      courses_tran_kod_id['BI-BEZ']
     )

#PST
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-PST'], 
      courses_tran_kod_id['BIK-PST'], 
      courses_tran_kod_id['BI-PST.21'], 
      courses_tran_kod_id['BIE-PST.21'],
      courses_tran_kod_id['BIK-PST.21']],
     
      courses_tran_kod_id['BI-PST']
     )

#SI1.2
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-SI1'], 
      courses_tran_kod_id['BIK-SI1'], 
      courses_tran_kod_id['BI-SI1'], 
      courses_tran_kod_id['BIE-SI1.2'],
      courses_tran_kod_id['BIK-SI1.2'],
      courses_tran_kod_id['BIK-SWI.21'], 
      courses_tran_kod_id['BI-SWI.21'], 
      courses_tran_kod_id['BIE-SWI.21'],],
     
      courses_tran_kod_id['BI-SI1.2']
     )

#EMP
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-EMP'], 
      courses_tran_kod_id['BIK-EMP'], 
      courses_tran_kod_id['BI-EKP'], 
      courses_tran_kod_id['BIE-EKP'],
      courses_tran_kod_id['BIK-EKP'],
      courses_tran_kod_id['BI-EPD'], 
      courses_tran_kod_id['BIE-EPD'],
      courses_tran_kod_id['BIK-EPD'],
      courses_tran_kod_id['BIK-EPD.2'], 
      courses_tran_kod_id['BI-EPD.2'], 
      courses_tran_kod_id['BIE-EPD.2'],],
     
      courses_tran_kod_id['BI-EMP']
     )

#DPR
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-DPR'], 
      courses_tran_kod_id['BIK-DPR'], 
      courses_tran_kod_id['BI-PPR'], 
      courses_tran_kod_id['BIE-PPR'],
      courses_tran_kod_id['BIK-PPR']],
     
      courses_tran_kod_id['BI-DPR']
     )

#AG1
klasifikace_fact = klasifikace_fact.replace(
    [courses_tran_kod_id['BIE-AG1'], 
      courses_tran_kod_id['BIK-AG1']],
     
      courses_tran_kod_id['BI-AG1']
     )

In [17]:
len(predmet_dim_17)

5665

In [18]:
len(predmet_dim)

5656

In [ ]:
predmet_dim_17[~predmet_dim_17.predmet_id.isin(predmet_dim.predmet_id.unique())]

In [ ]:
path_file = os.sep.join(['data_mar_17', 'predmet_dim.csv'])
predmet_dim_17 = pd.read_csv(path_file, sep=";")

In [ ]:
predmet_dim[predmet_dim.predmet_id == courses_tran_kod_id['BIK-EKP']]

In [ ]:
predmet_dim_17[predmet_dim_17.predmet_id == courses_tran_kod_id['BI-EPD']]

In [ ]:
courses_tran_kod_id['BI-EPD']

In [ ]:
klasifikace_fact[klasifikace_fact.predmet_id == courses_tran_kod_id['BI-SI1']]

In [19]:
# vsichni studenti, kteri studuji v cj a jedna se o prezencni formu studia
studium_dim_bak_09 = studium_dim[(studium_dim['jazyk_vyuky'] == 'CS')
                             & (studium_dim['forma_studia'] == 'P')
                             & (studium_dim['typ_programu'] == 'B')]
studium_dim_mag_09 = studium_dim[(studium_dim['jazyk_vyuky'] == 'CS')
                             & (studium_dim['forma_studia'] == 'P')
                             & (studium_dim['typ_programu'] == 'N')]

# uspesni studenti bakalar
successful_students_bak = studium_dim_bak_09[(studium_dim_bak_09['ukonceni_zpusob'] == 1)]['studium_id'].unique()
# neuspesni studetni bakalar
failed_students_bak = studium_dim_bak_09[(studium_dim_bak_09['ukonceni_zpusob'] != 1)
                             & (studium_dim_bak_09['ukonceni_zpusob'].notna())]['studium_id'].unique()

# uspesni studenti magistr
successful_students_mag = studium_dim_mag_09[(studium_dim_mag_09['ukonceni_zpusob'] == 1)]['studium_id'].unique()
# neuspesni studenti magistr
failed_students_mag = studium_dim_mag_09[(studium_dim_mag_09['ukonceni_zpusob'] != 1)
                             & (studium_dim_mag_09['ukonceni_zpusob'].notna())]['studium_id'].unique()

In [20]:
student_id_bak_09 = studium_dim_bak_09.studium_id.unique()
student_id_mag_09 = studium_dim_mag_09.studium_id.unique()

#pomocna promenna array vsech pp bak pred
courses_baks = courses_baks[(courses_baks['kod_predmetu'] != 'BI-BAP')
                            & (courses_baks['kod_predmetu'] != 'BI-BPR')]
courses_kod_bak = courses_baks['kod_predmetu'].unique()

#pomocna promenna array vsech pp mag pred
courses_mag = courses_mag[(courses_mag['kod_predmetu'] != 'MI-MPR')
                            & (courses_mag['kod_predmetu'] != 'MI-DIP')]
courses_kod_mag = courses_mag['kod_predmetu'].unique()

courses_id_bak = []
for course in courses_kod_bak:
    courses_id_bak.append(courses_tran_kod_id[course])

courses_id_mag = []
for course in courses_kod_mag:
    courses_id_mag.append(courses_tran_kod_id[course])

In [21]:
klasifikace_fact_changed = klasifikace_fact.copy(deep=True)

# pokud je zapocteno, zakonceno i znamka nan, zmena znamky na 4
klasifikace_fact_changed.loc[(klasifikace_fact_changed.semestr_id != 'B212')
                     & (klasifikace_fact_changed.znamka.isna())
                     & (klasifikace_fact_changed.zapocteno != 'Z')
                     & (klasifikace_fact_changed.zakonceno.isna()), 'znamka'] = 4

# pokud je vyplnena znamka 4, doplneni zapocteno a zakonceno
klasifikace_fact_changed.loc[(klasifikace_fact_changed.znamka == 4), 'zapocteno'] = 0
klasifikace_fact_changed.loc[(klasifikace_fact_changed.znamka == 4), 'zakonceno'] = 0

# doplneni zakonceno na 1, pokud je znamka jina nez nan nebo 4
klasifikace_fact_changed.loc[(klasifikace_fact_changed.znamka != 4) 
                             & (klasifikace_fact_changed.znamka.notna()), 'zakonceno'] = 1

# Prepsani N a Z u zapocteno na 0 a 1
klasifikace_fact_changed.loc[(klasifikace_fact_changed.zapocteno == 'N'), 'zapocteno'] = 0
klasifikace_fact_changed.loc[(klasifikace_fact_changed.zapocteno == 'Z'), 'zapocteno'] = 1

In [22]:
# vsichni studenti bez bakalarky a diplomky
klasifikace_fact_bak_09 = klasifikace_fact_changed[
    (klasifikace_fact_changed['studium_id'].isin(student_id_bak_09))].sort_values(by=['poradi_zapisu'])

klasifikace_fact_mag_09 = klasifikace_fact_changed[
    (klasifikace_fact_changed['studium_id'].isin(student_id_mag_09))].sort_values(by=['poradi_zapisu'])

In [23]:
#matice klasikace bakalar
courses_matrix_bak = pd.DataFrame(index=student_id_bak_09, columns=courses_kod_bak)  

for index, row in klasifikace_fact_bak_09[klasifikace_fact_bak_09.predmet_id.isin(courses_id_bak)].iterrows():
    if not math.isnan(row['znamka']):
        courses_matrix_bak[courses_tran_id_kod[row['predmet_id']]][row['studium_id']] = row['znamka']

In [24]:
is_nan = courses_matrix_bak[(courses_matrix_bak.index.isin(successful_students_bak))].drop(columns=['BI-AG1']).isnull()
row_has_NaN = is_nan.any(axis=1)
rows_with_NaN = courses_matrix_bak[(courses_matrix_bak.index.isin(successful_students_bak))].drop(columns=['BI-AG1'])[row_has_NaN]

In [25]:
ind = rows_with_NaN.index.to_numpy()

In [ ]:
ind

In [26]:
cm = courses_matrix_bak[(courses_matrix_bak.index.isin(successful_students_bak))]
cm[cm.isnull().all(axis=1)]

Empty DataFrame
Columns: [BI-PA1, BI-PAI, BI-CAO, BI-PS1, BI-MLO, BI-ZMA, BI-PA2, BI-DBS, BI-SAP, BI-LIN, BI-AG1, BI-AAG, BI-ZDM, BI-OSY, BI-PSI, BI-BEZ, BI-PST, BI-DPR, BI-SI1.2, BI-EMP]
Index: []

In [ ]:
klasifikace_fact[(klasifikace_fact.studium_id == 13518606)]

In [ ]:
studium_dim[(studium_dim.studium_id ==  12034706)]

In [27]:
#matice klasikace bakalar
courses_matrix_mag = pd.DataFrame(index=student_id_mag_09, columns=courses_kod_mag)  

for index, row in klasifikace_fact_mag_09[klasifikace_fact_mag_09.predmet_id.isin(courses_id_mag)].iterrows():
    if not math.isnan(row['znamka']):
        courses_matrix_mag[courses_tran_id_kod[row['predmet_id']]][row['studium_id']] = row['znamka']

In [28]:
# uspesni studenti bakalar
successful_students_bak = studium_dim_bak_09[(studium_dim_bak_09['ukonceni_zpusob'] == 1)]['studium_id'].unique()
# neuspesni studetni bakalar
failed_students_bak = studium_dim_bak_09[(studium_dim_bak_09['ukonceni_zpusob'] != 1)
                             & (studium_dim_bak_09['ukonceni_zpusob'].notna())]['studium_id'].unique()

# uspesni studenti magistr
successful_students_mag = studium_dim_mag_09[(studium_dim_mag_09['ukonceni_zpusob'] == 1)]['studium_id'].unique()
# neuspesni studenti magistr
failed_students_mag = studium_dim_mag_09[(studium_dim_mag_09['ukonceni_zpusob'] != 1)
                             & (studium_dim_mag_09['ukonceni_zpusob'].notna())]['studium_id'].unique()

In [29]:
# zmena datum_zahajeni pouze na rok a zmena ze stringu na int
studium_dim['datum_zahajeni'] = studium_dim['datum_zahajeni'].apply(lambda x: x.split('-')[0])

studium_dim['datum_ukonceni'] = studium_dim['datum_ukonceni'].fillna('0')
studium_dim['datum_ukonceni'] = studium_dim['datum_ukonceni'].apply(lambda x: x.split('-')[0])

studium_dim['rok_maturity'] = studium_dim['rok_maturity'].fillna('0')
studium_dim['rok_maturity'] = studium_dim['rok_maturity'].apply(lambda x: x.split('-')[0])

studium_dim['datum_zahajeni'] = pd.to_numeric(studium_dim['datum_zahajeni'])
studium_dim['datum_ukonceni'] = pd.to_numeric(studium_dim['datum_ukonceni'])
studium_dim['rok_maturity'] = pd.to_numeric(studium_dim['rok_maturity'])

In [30]:
# studium_sub a student_sub

# nahrazeni datumu zahajeni studia a roku maturity, jejich rozdilem
# pokud jedna z hodnot chybi je hodnota nahrazena prumernym rozdilem
studium_sub = studium_dim[['studium_id', 'datum_zahajeni', 'rok_maturity']]
studium_sub['maturita_nastup_rozdil'] = studium_sub['datum_zahajeni'] - studium_sub['rok_maturity']
studium_sub.loc[studium_sub['maturita_nastup_rozdil'] > 1000, 'maturita_nastup_rozdil'] = math.nan
studium_sub.loc[studium_sub['maturita_nastup_rozdil'] < 0, 'maturita_nastup_rozdil'] = math.nan
rozdil_mean = round(studium_sub['maturita_nastup_rozdil'].mean())
studium_sub['maturita_nastup_rozdil'] = studium_sub['maturita_nastup_rozdil'].fillna(rozdil_mean)
studium_sub = studium_sub.drop(columns=['datum_zahajeni', 'rok_maturity'])

# nahrazeni sloupce statni_prislusnost_nazev, novym sloupcem je_cech (1 - pokud ano, 0 - pokud ne)
student_sub = student_dim[['studium_id', 'pohlavi_kod', 'statni_prislusnost_nazev']]
student_sub['je_cech'] = math.nan
student_sub.loc[student_sub.statni_prislusnost_nazev == 'Česko', 'je_cech'] = 1
student_sub.loc[student_sub.statni_prislusnost_nazev != 'Česko', 'je_cech'] = 0
student_sub = student_sub.drop(columns='statni_prislusnost_nazev')

<ipython-input-30-c104f0516a12>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studium_sub['maturita_nastup_rozdil'] = studium_sub['datum_zahajeni'] - studium_sub['rok_maturity']
/home/kapitann/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/kapitann/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
<ipython-input-30-c104f0516a12>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studium_sub['maturita_nastup_rozdil'] = studium_sub['maturita_nastup_rozdil'].fillna(rozdil_mean)
<ipython-input-30-c104f0516a12>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student_sub['je_cech'] = math.nan

In [31]:
matrix_bak = student_sub.merge(studium_sub, how='outer', on='studium_id')
matrix_bak['dostudoval_uspesne'] = 0

matrix_bak.loc[matrix_bak.studium_id.isin(successful_students_bak), 'dostudoval_uspesne'] = 1
matrix_bak.drop(matrix_bak[(~matrix_bak.studium_id.isin(failed_students_bak))
                          & (~matrix_bak.studium_id.isin(successful_students_bak))].index, inplace=True)

ids_bak = matrix_bak['studium_id']
matrix_bak[ids_bak.isin(ids_bak[ids_bak.duplicated()])]

matrix_bak = matrix_bak.merge(courses_matrix_bak, how='inner', left_on='studium_id', right_index=True)
    
matrix_bak = matrix_bak.drop_duplicates(subset=['studium_id'])
matrix_bak = matrix_bak.set_index('studium_id')
matrix_bak = matrix_bak.replace('M', 0)
matrix_bak = matrix_bak.replace('Z', 1)

In [ ]:
print(len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].notna())]))
print(len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)]))
print(len(matrix_bak[(matrix_bak['BI-AG1'].notna())]))
print(len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-DPR'].notna())]))
print(len(matrix_bak[(matrix_bak['BI-DPR'].notna())]))

print(len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 0)]))

In [32]:
studium_id_bak_15 = studium_dim[(studium_dim['datum_zahajeni'] >= 2015) 
                             & (studium_dim['jazyk_vyuky'] == 'CS')
                             & (studium_dim['forma_studia'] == 'P')
                             & (studium_dim['typ_programu'] == 'B')].studium_id.unique()

In [33]:
ag1_nan = courses_matrix_bak[ (courses_matrix_bak.index.isin(studium_id_bak_15)) &
    (courses_matrix_bak.index.isin(successful_students_bak))
                            & (courses_matrix_bak['BI-AG1'].isna())].index.to_numpy()

In [ ]:
len(ag1_nan)

In [ ]:
len(courses_matrix_bak[(courses_matrix_bak.index.isin(successful_students_bak)) & (courses_matrix_bak['BI-AG1'].isna())])

In [ ]:
len(ind)

In [34]:
ind_ag1 = np.concatenate((ind, ag1_nan), axis=None)
ind_ag1 = np.unique(ind_ag1)

In [ ]:
len(ind_ag1)

In [ ]:
ind_ag1

In [35]:
ind_ag1_df = pd.DataFrame(columns=['studium_id'])

ind_ag1_df.studium_id = ind_ag1

path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_nan_PP_studium_id.csv'])
ind_ag1_df.to_csv(path_file, index=True)

In [ ]:
studs_pa1 = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PA1'].isna())].index.unique()

studs_pa1.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PA1'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_pa1_studium_id.csv'])
studs_pa1.to_csv(path_file, index=True)

In [ ]:
studs_pai = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PAI'].isna())].index.unique()

studs_pai.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PAI'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_pai_studium_id.csv'])
studs_pai.to_csv(path_file, index=True)

In [ ]:
studs_cao = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-CAO'].isna())].index.unique()

studs_cao.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-CAO'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_cao_studium_id.csv'])
studs_cao.to_csv(path_file, index=True)

In [ ]:
studs_ps1 = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PS1'].isna())].index.unique()

studs_ps1.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PS1'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_ps1_studium_id.csv'])
studs_ps1.to_csv(path_file, index=True)

In [ ]:
studs_mlo = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-MLO'].isna())].index.unique()

studs_mlo.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-MLO'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_mlo_studium_id.csv'])
studs_mlo.to_csv(path_file, index=True)

In [ ]:
studs_zma = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-ZMA'].isna())].index.unique()

studs_zma.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-ZMA'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_zma_studium_id.csv'])
studs_zma.to_csv(path_file, index=True)

In [ ]:
studs_pa2 = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PA2'].isna())].index.unique()

studs_pa2.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PA2'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_pa2_studium_id.csv'])
studs_pa2.to_csv(path_file, index=True)

In [ ]:
studs_dbs = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-DBS'].isna())].index.unique()

studs_dbs.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-DBS'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_dbs_studium_id.csv'])
studs_dbs.to_csv(path_file, index=True)

In [ ]:
studs_sap = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-SAP'].isna())].index.unique()

studs_sap.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-SAP'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_sap_studium_id.csv'])
studs_sap.to_csv(path_file, index=True)

In [ ]:
studs_lin = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-LIN'].isna())].index.unique()

studs_lin.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-LIN'].isna())].index.unique())

In [ ]:
matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-LIN'].isna())]

In [ ]:
klasifikace_fact[(klasifikace_fact.studium_id == 9222706)
                & (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-LIN'])]

In [ ]:
studium_dim[studium_dim.studium_id == 9222706]

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_lin_studium_id.csv'])
studs_lin.to_csv(path_file, index=True)

In [ ]:
studs_ag1 = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].isna())
          & (matrix_bak.index.isin(studium_id_bak_15))].index.unique()

studs_ag1.studium_id = studs

In [ ]:
ag1_st = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].isna())
          & (matrix_bak.index.isin(studium_id_bak_15))].index.unique()

In [ ]:
st_gra_efa_uzn = klasifikace_fact[(klasifikace_fact.studium_id.isin(ag1_st))
                & ((klasifikace_fact.predmet_id == courses_tran_kod_id['BI-GRA'])
                  | (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-EFA']))].studium_id.unique()

In [ ]:
ag1_st_chybi = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].isna())
          & (matrix_bak.index.isin(studium_id_bak_15))
          & (~matrix_bak.index.isin(st_gra_efa_uzn))].index.unique()

In [ ]:
len(ag1_st_chybi)

In [ ]:
studium_dim[studium_dim.studium_id == 12375406]

In [ ]:
student_dim

In [ ]:
ag1_st_chybi

In [ ]:
studium_dim[studium_dim.studium_id.isin(ag1_st)]

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].isna())
          & (matrix_bak.index.isin(studium_id_bak_15))].index.unique())

In [ ]:
matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AG1'].isna())
          & (matrix_bak.index.isin(studium_id_bak_15))]

In [ ]:
studs_ag1 = pd.DataFrame(columns=['studium_id'])

studs = ag1_st_chybi

studs_ag1.studium_id = studs

In [ ]:
studs_ag1

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_ag1_studium_id.csv'])
studs_ag1.to_csv(path_file, index=True)

In [ ]:
studs_aag = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AAG'].isna())].index.unique()

studs_aag.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-AAG'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_aag_studium_id.csv'])
studs_aag.to_csv(path_file, index=True)

In [ ]:
studs_zdm = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-ZDM'].isna())].index.unique()

studs_zdm.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-ZDM'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_zdm_studium_id.csv'])
studs_zdm.to_csv(path_file, index=True)

In [ ]:
studs_osy = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-OSY'].isna())].index.unique()

studs_osy.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-OSY'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_osy_studium_id.csv'])
studs_osy.to_csv(path_file, index=True)

In [ ]:
studs_psi = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PSI'].isna())].index.unique()

studs_psi.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PSI'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_psi_studium_id.csv'])
studs_psi.to_csv(path_file, index=True)

In [ ]:
studs_bez = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-BEZ'].isna())].index.unique()

studs_bez.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-BEZ'].isna())].index.unique())

In [ ]:
matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-BEZ'].isna())]

In [ ]:
klasifikace_fact[(klasifikace_fact.studium_id == 4052006)
                & (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-BEZ'])]

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_bez_studium_id.csv'])
studs_bez.to_csv(path_file, index=True)

In [ ]:
studs_pst = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PST'].isna())].index.unique()

studs_pst.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-PST'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_pst_studium_id.csv'])
studs_pst.to_csv(path_file, index=True)

In [ ]:
studs_dpr = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-DPR'].isna())].index.unique()

studs_dpr.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-DPR'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_dpr_studium_id.csv'])
studs_dpr.to_csv(path_file, index=True)

In [ ]:
chybi_si = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-SI1.2'].isna())].index.unique()

In [ ]:
len(chybi_si)

In [ ]:
courses_tran_kod_id['BI-ZSI']

In [ ]:
len(klasifikace_fact[(klasifikace_fact.studium_id.isin(chybi_si))
                & (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-ZSI'])].studium_id.unique())

In [ ]:
klasifikace_fact[(klasifikace_fact.studium_id.isin(chybi_si))
                & (klasifikace_fact.predmet_id == courses_tran_kod_id['BI-ZSI'])]

In [ ]:
studs_si1 = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-SI1.2'].isna())].index.unique()

studs_si1.studium_id = studs

In [ ]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-SI1.2'].isna())].index.unique())

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_si1_studium_id.csv'])
studs_si1.to_csv(path_file, index=True)

In [36]:
studs_emp = pd.DataFrame(columns=['studium_id'])

studs = matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-EMP'].isna())].index.unique()

studs_emp.studium_id = studs

In [37]:
len(matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-EMP'].isna())].index.unique())

1

In [39]:
matrix_bak

,pohlavi_kod,je_cech,maturita_nastup_rozdil,dostudoval_uspesne,BI-PA1,BI-PAI,BI-CAO,BI-PS1,BI-MLO,BI-ZMA,BI-PA2,BI-DBS,BI-SAP,BI-LIN,BI-AG1,BI-AAG,BI-ZDM,BI-OSY,BI-PSI,BI-BEZ,BI-PST,BI-DPR,BI-SI1.2,BI-EMP
studium_id,,,,,,,,,,,,,,,,,,,,,,,,
1578106,0,0.0,2.0,1,2.0,1.5,1.5,2.0,2.0,2.0,3.0,2.0,1.5,1.0,NaN,2.0,3.0,1.5,2.0,3.0,1.5,1.5,NaN,3.0
1584806,0,0.0,3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19374606,0,1.0,12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4783406,0,1.0,2.0,0,4.0,3.0,1.5,4.0,2.5,2.5,NaN,NaN,4.0,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
8396706,1,1.0,4.0,0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815106,0,1.0,0.0,0,2.5,2.0,3.0,2.5,2.0,2.0,3.0,2.5,3.0,3.0,NaN,3.0,3.0,3.0,3.0,4.0,2.5,2.5,NaN,4.0
6280106,0,1.0,4.0,0,1.5,2.0,2.0,1.0,2.0,4.0,2.5,4.0,2.0,4.0,NaN,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
3727706,0,1.0,1.0,1,1.0,2.0,1.0,1.5,1.5,1.5,1.5,1.5,1.0,1.5,NaN,1.0,2.0,1.0,2.0,1.5,1.0,1.0,1.0,1.5
2816306,0,1.0,10.0,0,1.0,4.0,4.0,4.0,2.0,2.0,4.0,NaN,4.0,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
1577906,0,1.0,9.0,0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)
          & (matrix_bak['BI-EMP'].isna())]

,pohlavi_kod,je_cech,maturita_nastup_rozdil,dostudoval_uspesne,BI-PA1,BI-PAI,BI-CAO,BI-PS1,BI-MLO,BI-ZMA,BI-PA2,BI-DBS,BI-SAP,BI-LIN,BI-AG1,BI-AAG,BI-ZDM,BI-OSY,BI-PSI,BI-BEZ,BI-PST,BI-DPR,BI-SI1.2,BI-EMP
studium_id,,,,,,,,,,,,,,,,,,,,,,,,
3723906,0,1.0,0.0,1,1.0,1.5,1.0,1.0,2.0,1.5,2.0,2.5,1.5,2.0,NaN,2.0,3.0,3.0,3.0,2.5,2.5,2.0,2.5,NaN

In [ ]:
path_file = os.sep.join([data_adr, 'chybejici_data', 'uspesni_emp_studium_id.csv'])
studs_emp.to_csv(path_file, index=True)

In [ ]:
matrix_bak[(matrix_bak.loc[:, 'BI-PA1':'BI-EMP'].isna()) & (matrix_bak['dostudoval_uspesne'] == 1)]

In [ ]:
courses_kod_bak

In [ ]:
matrix_mag = student_sub.merge(studium_sub, how='outer', on='studium_id')
matrix_mag['dostudoval_uspesne'] = 0

matrix_mag.loc[matrix_mag.studium_id.isin(successful_students_mag), 'dostudoval_uspesne'] = 1
matrix_mag.drop(matrix_mag[(~matrix_mag.studium_id.isin(failed_students_mag))
                          & (~matrix_mag.studium_id.isin(successful_students_mag))].index, inplace=True)

ids_mag = matrix_mag['studium_id']
matrix_mag[ids_mag.isin(ids_mag[ids_mag.duplicated()])]

matrix_mag = matrix_mag.merge(courses_matrix_mag, how='inner', left_on='studium_id', right_index=True)
    
matrix_mag = matrix_mag.drop_duplicates(subset=['studium_id'])
matrix_mag = matrix_mag.set_index('studium_id')
matrix_mag = matrix_mag.replace('M', 0)
matrix_mag = matrix_mag.replace('Z', 1)

In [ ]:
matrix_bak[(matrix_bak['dostudoval_uspesne'] == 1)]